name: Build
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        name: Build
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v4
        - run: |
            git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/olcpp/apps.git
            npm ci
            npx gh-pages -d @build -u “github-actions-bot <support+actions@github.com>” 
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }} 